# Generated by Django 5.0.6 on 2024-07-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_voter_education_alter_voter_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='email',
            field=models.EmailField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
