# Generated by Django 5.0.6 on 2024-07-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_voter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='password_hashed',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voter',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
