# Generated by Django 5.0.6 on 2024-07-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_voter_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='password_hashed',
        ),
        migrations.AddField(
            model_name='voter',
            name='password',
            field=models.CharField(default='none', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voter',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
