# Generated by Django 5.0.6 on 2024-07-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_voter_password_hashed_voter_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
