# Generated by Django 5.0.6 on 2024-07-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_state_alter_candidate_party_alter_voter_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='voted_ind',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='votes_dem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='votes_rep',
            field=models.IntegerField(default=0),
        ),
    ]
