# Generated by Django 5.0.6 on 2024-07-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_voted_ind_state_votes_ind'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='party',
            field=models.CharField(choices=[('Republican', 'Republican'), ('Democrat', 'Democrat'), ('Independent', 'Independent')], default='Democrat', max_length=200),
        ),
    ]
