# Generated by Django 5.0.6 on 2024-07-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_voter_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='party',
            field=models.CharField(default='Democrat', max_length=200),
        ),
    ]
