# Generated by Django 5.0.6 on 2024-07-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_poll_state_electoral_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='percetn_dem',
            new_name='percent_dem',
        ),
    ]
